# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babynamebook', '0002_auto_20170703_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tree_upload',
        ),
    ]
