# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babynamebook', '0003_remove_book_tree_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='tree_upload',
            field=models.FileField(default=None, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
    ]
