# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babynamebook', '0006_auto_20170704_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default='x', max_length=1),
            preserve_default=False,
        ),
    ]
