# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babynamebook', '0008_auto_20170705_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='names',
            field=models.ManyToManyField(to='babynamebook.Name'),
        ),
    ]
